# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-01-17 12:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Enquiry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255, null=True, verbose_name='First Name(s)')),
                ('last_name', models.CharField(max_length=255, null=True, verbose_name='Last Name')),
                ('company', models.CharField(blank=True, max_length=255, verbose_name='Company')),
                ('tel', models.CharField(blank=True, max_length=30, verbose_name='Telephone')),
                ('email', models.EmailField(max_length=254, null=True, verbose_name='Email')),
                ('text', models.TextField(null=True, verbose_name='Enquiry text')),
                ('datemade', models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='Enquiry Date')),
                ('frompage', models.CharField(blank=True, max_length=50, verbose_name='Made on page')),
                ('request_meta', models.TextField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=255, null=True)),
                ('ip_blocklist_response', models.TextField(blank=True, null=True)),
                ('ip_blocklist', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Enquiries',
            },
        ),
    ]
