from django.conf import settings

UBIQUITOUS_CONTACT_FORM_RECIPIENTS = getattr(settings, "UBIQUITOUS_CONTACT_FORM_RECIPIENTS", [])
UBIQUITOUS_CONTACT_FORM_SEND_RECEIPT = getattr(settings, "UBIQUITOUS_CONTACT_FORM_SEND_RECEIPT", True)
UBIQUITOUS_CONTACT_FORM_STAGING_EMAIL_ADDRESS = getattr(settings, "UBIQUITOUS_CONTACT_FORM_STAGING_EMAIL_ADDRESS", [])    
UBIQUITOUS_CONTACT_FORM_CHECK_BLOCKLIST = getattr(settings, "UBIQUITOUS_CONTACT_FORM_CHECK_BLOCKLIST", False)
UBIQUITOUS_CONTACT_FORM_CONTEXT_KEY = getattr(settings, "UBIQUITOUS_CONTACT_FORM_CONTEXT_KEY", "footer_contact_form")
UBIQUITOUS_CONTACT_FORM_THANKS_URL = getattr(settings, "UBIQUITOUS_CONTACT_FORM_THANKS_URL", "/ubiquitous_contactform/thanks")
UBIQUITOUS_CONTACT_FORM_RECEIPT_SUBJECT = getattr(settings, "UBIQUITOUS_CONTACT_FORM_SUBJECT", "Thanks for your enquiry")
