# Generated by Django 3.1.5 on 2021-03-31 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ubiquitous_contactform', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiry',
            name='ip_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
